-- src/main/resources/db/migration/V1.0.1__db_initialization.sql

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;

--
-- Tworzenie tablic
--

-- pytanie
CREATE TABLE public.pytanie (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        id_hipoteza INTEGER,
        id_pytanie INTEGER,
        tekst VARCHAR(255),
        utworzenie_timestamp TIMESTAMP WITHOUT TIME ZONE,
        edycja_timestamp TIMESTAMP WITHOUT TIME ZONE,
        CONSTRAINT pk_pytanie PRIMARY KEY (id)
);

CREATE TABLE public.pytanie_kod (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        id_pytanie INTEGER NOT NULL,
        id_kod INTEGER NOT NULL,
        CONSTRAINT pk_pytanie_kod PRIMARY KEY (id)
);

CREATE TABLE public.pytanie_grupa_kodow (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        id_pytanie INTEGER NOT NULL,
        id_grupa_kodow INTEGER NOT NULL,
        CONSTRAINT pk_pytanie_grupa_kodow PRIMARY KEY (id)
);

-- cytat
CREATE TABLE public.cytat (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        id_kod INTEGER,
        id_wywiad INTEGER,
        numer_linijki INTEGER,
        tekst VARCHAR(255),
        utworzenie_timestamp TIMESTAMP WITHOUT TIME ZONE,
        edycja_timestamp TIMESTAMP WITHOUT TIME ZONE,
        CONSTRAINT pk_cytat PRIMARY KEY (id)
);

-- badanie
CREATE TABLE public.badanie (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        nazwa VARCHAR(255),
        utworzenie_timestamp TIMESTAMP WITHOUT TIME ZONE,
        edycja_timestamp TIMESTAMP WITHOUT TIME ZONE,
        CONSTRAINT pk_badanie PRIMARY KEY (id)
);

-- wywiad
CREATE TABLE public.wywiad (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        id_badanie INTEGER,
        nazwa VARCHAR(255),
        tekst VARCHAR(2500),
        utworzenie_timestamp TIMESTAMP WITHOUT TIME ZONE,
        edycja_timestamp TIMESTAMP WITHOUT TIME ZONE,
        CONSTRAINT pk_wywiad PRIMARY KEY (id)
);

-- hipoteza
CREATE TABLE public.hipoteza (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        id_badanie INTEGER,
        id_pytanie INTEGER,
        tekst VARCHAR(255),
        utworzenie_timestamp TIMESTAMP WITHOUT TIME ZONE,
        edycja_timestamp TIMESTAMP WITHOUT TIME ZONE,
        CONSTRAINT pk_hipoteza PRIMARY KEY (id)
);

-- grupa_kodow
CREATE TABLE public.grupa_kodow (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        id_badanie INTEGER,
        nazwa VARCHAR(255),
        utworzenie_timestamp TIMESTAMP WITHOUT TIME ZONE,
        edycja_timestamp TIMESTAMP WITHOUT TIME ZONE,
        CONSTRAINT pk_grupa_kodow PRIMARY KEY (id)
);

-- kod
CREATE TABLE public.kod (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        id_grupa_kodow INTEGER,
        id_badanie INTEGER,
        nazwa VARCHAR(255),
        utworzenie_timestamp TIMESTAMP WITHOUT TIME ZONE,
        edycja_timestamp TIMESTAMP WITHOUT TIME ZONE,
        CONSTRAINT pk_kod PRIMARY KEY (id)
);


--
-- Łączenie tablic
--

-- pytanie
ALTER TABLE public.pytanie_kod ADD CONSTRAINT FK_PYTANIE_KOD_ON_ID_PYTANIE FOREIGN KEY (id_pytanie) REFERENCES public.pytanie (id);

ALTER TABLE public.pytanie_kod ADD CONSTRAINT FK_PYTANIE_KOD_ON_ID_KOD FOREIGN KEY (id_kod) REFERENCES public.kod (id);

ALTER TABLE public.pytanie_grupa_kodow ADD CONSTRAINT FK_PYTANIE_KOD_ON_ID_PYTANIE FOREIGN KEY (id_pytanie) REFERENCES public.pytanie (id);

ALTER TABLE public.pytanie_grupa_kodow ADD CONSTRAINT FK_PYTANIE_KOD_ON_ID_GRUPA_KODOW FOREIGN KEY (id_grupa_kodow) REFERENCES public.grupa_kodow (id);

ALTER TABLE public.pytanie ADD CONSTRAINT FK_PYTANIE_ON_ID_HIPOTEZA FOREIGN KEY (id_hipoteza) REFERENCES public.hipoteza (id);

ALTER TABLE public.pytanie ADD CONSTRAINT FK_PYTANIE_ON_ID_PYTANIE FOREIGN KEY (id_pytanie) REFERENCES public.pytanie (id);

-- cytat
ALTER TABLE public.cytat ADD CONSTRAINT FK_CYTAT_ON_ID_KOD FOREIGN KEY (id_kod) REFERENCES public.kod (id);

ALTER TABLE public.cytat ADD CONSTRAINT FK_CYTAT_ON_ID_WYWIAD FOREIGN KEY (id_wywiad) REFERENCES public.wywiad (id);

-- wywiad
ALTER TABLE public.wywiad ADD CONSTRAINT FK_WYWIAD_ON_ID_BADANIE FOREIGN KEY (id_badanie) REFERENCES public.badanie (id);

-- hipoteza
ALTER TABLE public.hipoteza ADD CONSTRAINT FK_HIPOTEZA_ON_ID_BADANIE FOREIGN KEY (id_badanie) REFERENCES public.badanie (id);

ALTER TABLE public.hipoteza ADD CONSTRAINT FK_HIPOTEZA_ON_ID_PYTANIE FOREIGN KEY (id_pytanie) REFERENCES public.pytanie (id);

-- grupa_kodow
ALTER TABLE public.grupa_kodow ADD CONSTRAINT FK_GRUPA_KODOW_ON_ID_BADANIE FOREIGN KEY (id_badanie) REFERENCES public.badanie (id);

-- kod
ALTER TABLE public.kod ADD CONSTRAINT FK_KOD_ON_ID_GRUPA_KODOW FOREIGN KEY (id_grupa_kodow) REFERENCES public.grupa_kodow (id);

ALTER TABLE public.kod ADD CONSTRAINT FK_KOD_ON_ID_BADANIE FOREIGN KEY (id_badanie) REFERENCES public.badanie (id);

